@extends('site.layouts.app')
@section('title', __('athar.request'))
@section('content')
@include('site.includes.page-hero',['title'=>__('athar.request'),'kicker'=>__('athar.home.kicker'),'intro'=>__('athar.form.intro')])
<section class="section"><div class="container split"><div class="form-card" data-reveal><h2>{{ __('athar.form.title') }}</h2><p class="muted">{{ __('athar.form.intro') }}</p>@if($errors->any())<div class="alert alert--error">{{ $errors->first() }}</div>@endif<form method="post" action="{{ route('site.service_request.store') }}" enctype="multipart/form-data" class="form-grid">@csrf
<div class="field"><label>{{ __('athar.contact.name') }} *</label><input name="name" value="{{ old('name') }}" required></div><div class="field"><label>{{ __('athar.contact.company') }}</label><input name="company" value="{{ old('company') }}"></div><div class="field"><label>{{ __('athar.contact.email') }} *</label><input type="email" name="email" value="{{ old('email') }}" required></div><div class="field"><label>{{ __('athar.contact.phone') }} *</label><input type="tel" name="phone" value="{{ old('phone') }}" required></div>
<div class="field"><label>{{ __('athar.form.service') }} *</label><select name="service_category_id" required><option value="">{{ __('athar.form.service') }}</option>@foreach($serviceCategories as $category)<option value="{{ $category->id }}" @selected(old('service_category_id',request('service'))==$category->id)>{{ optional($category->transNow)->title ?? __('athar.fallback.service') }}</option>@endforeach</select></div><div class="field"><label>{{ __('athar.form.timeline') }}</label><select name="timeline"><option value="Flexible">{{ app()->getLocale()==='ar'?'مرنة':'Flexible' }}</option><option value="1-3 months">{{ app()->getLocale()==='ar'?'من شهر إلى 3 أشهر':'1-3 months' }}</option><option value="3-6 months">{{ app()->getLocale()==='ar'?'من 3 إلى 6 أشهر':'3-6 months' }}</option></select></div>
<div class="field field--wide"><label>{{ __('athar.contact.message') }} *</label><textarea name="message" required>{{ old('message') }}</textarea></div><div class="field field--wide"><label>{{ __('athar.form.attachment') }}</label><input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png,.zip"></div><div class="field field--wide"><button class="btn btn--green btn--block" type="submit">{{ __('athar.form.submit') }}</button></div></form></div>
<div data-reveal><span class="eyebrow">{{ app()->getLocale()==='ar'?'كيف نعمل؟':'How we work' }}</span><h2 style="font-size:clamp(2rem,4vw,3.2rem)">{{ __('athar.home.process_title') }}</h2><div class="grid">@foreach(__('athar.steps') as $step)<div class="contact-card"><span class="icon-box">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><strong>{{ $step }}</strong><p class="muted">{{ __('athar.home.process_copy') }}</p></div>@endforeach</div></div></div></section>
@endsection
